Epic ETP-3504: Restore develop fallback for etendo_core epic checkout

diff --git a/pipelines/Jenkinsfile b/pipelines/Jenkinsfile
--- a/pipelines/Jenkinsfile
+++ b/pipelines/Jenkinsfile
@@ -171,9 +171,9 @@ pipeline {
 
                             // TODO: Remove this block to restore normal branch resolution for etendo_core
                             if (!isHotfixBranch && !(isFeatureBranch && env.EPIC_BRANCH)) {
-                                echo "Hardcoding branch epic/ETP-3504 for etendo_core (would otherwise resolve to develop)"
-                                coreCheckout = "git checkout epic/ETP-3504\n" +
-                                    "git checkout ${env.GIT_BRANCH} || echo 'Branch ${env.GIT_BRANCH} not found, keeping previous checkout'"
+                                coreCheckout = "git checkout epic/ETP-3504 || git checkout ${DEVELOP_BRANCH}\n" +
+                                               "git checkout ${env.GIT_BRANCH} || echo 'Branch ${env.GIT_BRANCH} not found, keeping previous checkout'"
+                                echo "Hardcoding etendo_core checkout to epic/ETP-3504 (fallback develop)"
                             }
                             echo "Checkout chain for etendo_core / com.etendoerp.go / schema_forge:\n${coreCheckout}"
 
